Repository the-collab-lab/tcl-74-smart-shopping-list, pull requests merged in 2024-09, with the labels that each got.

#25 Issue #9 : mark an item on shopping list as purchased and implement 24HR expiration for repurchasing.
  package-lock.json
  package.json
  src/App.jsx
  src/api/firebase.js
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/components/Toggle.css
  src/components/Toggle.jsx
  src/views/List.jsx
Labels: accessibility, enhancement

#26 Issue #8 - welcome prompt on List page
  src/views/List.jsx
Labels: accessibility, enhancement

#28 Issue #10: Error messages for empty item and duplicate item
  src/App.jsx
  src/views/ManageList.jsx
Labels: accessibility, enhancement

#29 Issue 11 Estimate next purchase date
  package-lock.json
  package.json
  src/api/firebase.js
  src/components/ListItem.jsx
  src/utils/dates.js
  src/views/List.jsx
Labels: bug fix, enhancement

#31 Issue #12: Delete Items from Shopping List
  src/api/firebase.js
  src/components/ListItem.jsx
  src/views/List.jsx
Labels: accessibility, enhancement

#30 Issue #13: Sort Items by Purchase Urgency
  src/api/firebase.js
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/utils/dates.js
  src/views/List.jsx
Labels: accessibility, enhancement

#35 Issue #14.3: Create <IconButton> Component
  index.html
  src/api/useAuth.jsx
  src/components/IconButton.jsx
  src/views/Layout.css
  src/views/Layout.jsx
Labels: enhancement

#37 Issue #14.2 Implement Disclosure component with collapsible content
  package-lock.json
  package.json
  src/App.jsx
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/components/Toggle.jsx
  src/views/Disclosure.css
  src/views/Disclosure.jsx
  src/views/Home.css
  src/views/Home.jsx
  src/views/List.jsx
  src/views/index.js
Labels: enhancement, refactoring
