Repository the-collab-lab/tcl-74-smart-shopping-list, pull requests merged in 2024-10, with the labels that each got.

#41 Issue #14.5: Implement LandingPage Component & Enhance Navigation UI
  package-lock.json
  public/logo.png
  src/App.jsx
  src/api/useAuth.jsx
  src/views/LandingPage.css
  src/views/LandingPage.jsx
  src/views/Layout.jsx
  src/views/ManageList.jsx
  src/views/index.js
Labels: enhancement

#42 Issue #15: Implement IconButton and update icon imports for consistent design and functionality
  index.html
  src/api/useAuth.jsx
  src/components/ListItem.jsx
  src/views/Disclosure.css
  src/views/Disclosure.jsx
  src/views/Home.css
  src/views/Home.jsx
  src/views/Layout.jsx
  src/views/ManageList.jsx
Labels: bug fix, enhancement, refactoring

#49 17. implement toast notifications on all messages not requiring user input
  package-lock.json
  package.json
  src/api/firebase.js
  src/components/ListItem.jsx
  src/index.css
  src/utils/notifications.js
  src/views/Home.jsx
  src/views/List.jsx
  src/views/ManageList.jsx
Labels: bug fix, refactoring

#51 Issue #18: Implement Modal dialog box for Share List and Create a List functionality
  src/components/IconButton.jsx
  src/components/ListItem.jsx
  src/components/ModalDialog.jsx
  src/views/CreateList.jsx
  src/views/Home.jsx
  src/views/ManageList.jsx
  src/views/Share.jsx
Labels: enhancement, refactoring

#54 Issue #19: Replace Plain CSS with Tailwind CSS on Landing and Team Pages; Add Mentors to Team Page
  src/assets/avatars/ejAvatar.png
  src/assets/avatars/jennyAvatar.jpg
  src/assets/avatars/meganAvatar.jpg
  src/assets/fulllogo_transparent.png
  src/components/Loading.jsx
  src/views/LandingPage.css
  src/views/LandingPage.jsx
  src/views/Team.jsx
Labels: enhancement, refactoring

#59 Issue #21: Implement TailwindCSS for ManageList page, refactor naming to AddItem page and modal close for Create List.
  src/App.jsx
  src/views/AddItem.jsx
  src/views/CreateList.jsx
  src/views/Disclosure.jsx
  src/views/Home.jsx
  src/views/Layout.jsx
  src/views/ManageList.jsx
  src/views/index.js
  tailwind.config.js
Labels: bug fix, enhancement, refactoring

#61 Dark/Light Mode Feature
  src/views/LandingPage.jsx
  src/views/Layout.jsx
  src/views/Team.jsx
  tailwind.config.js
Labels: accessibility, enhancement

#58 Issue #20: Finalize Logo and Favicon Integration
  index.html
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/assets/fulllogo_transparent.png
  src/assets/logo.png
  src/components/Loading.jsx
  src/favicon.ico
  src/views/LandingPage.jsx
  src/views/Layout.jsx
Labels: enhancement, refactoring
